### ISSUE TITLE
Problem while compiling and installing from source: `setuptools.command.test` has no attribute `test`

### ISSUE THREAD

**Issue by ahadji05** [equinor/segyio#575]
I was facing a problem while trying to compile and install from source following the instruction below:
```
git clone https://github.com/equinor/segyio
mkdir segyio/build
cd segyio/build
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
make
make install
```

After `make` I would received an error:
`AttributeError: module 'setuptools.command' has no attribute 'test'`

from file: `/segyio/python/setup.py` 
line 98: `cmdclass = { 'test': setuptools.command.test.test }, `

**Comment by ahadji05** [comment]
I solved the problem by adding: `from setuptools.command.test import *` 
at the beginning of file: `/segyio/python/setup.py`,

and then, change line `cmdclass = { 'test': setuptools.command.test.test }, ` to ` cmdclass = { 'test': test }, `

I am posting the problem and the solution, in case others with same setup as mine face it!

I am working on a `Ubuntu 22.04` system, with `Python 3.11.7`, `make 4.3` and `cmake 3.22.1`

**Comment by ajaust** [comment]
We think that this issue should be resolved now after merging #576. I close the issue, but please reopen it if the issue persists.
